name: CI/CD
on: [pull_request, push]

jobs:

  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.8.1'
    - run: flutter clean
    - run: flutter pub get
    - name: Build
      run: |
        flutter build appbundle
        flutter build apk
    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: apk-build
        path: build/app/outputs/bundle/release
    - name: Deploy
      uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
      with:
        appId: ${{secrets.FIREBASE_ANDROID_APPID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: testers
        release_notes: "a new version"
        file: build/app/outputs/apk/release/app-release.apk
