# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [master]
    # paths-ignore:
    #   - '**/README.md'
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # build:
  #   name: Build APK
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #   - uses: actions/setup-java@v1
  #     with:
  #       java-version: '12.x'
  #   - uses: subosito/flutter-action@v1
  #     with:
  #       flutter-version: '2.8.1'
  #   - run: flutter pub get
  #   - run: flutter build apk --debug --split-per-abi
  #   - name: Create a Release APK
  #     uses: ncipollo/release-action@v1
  #     with:
  #       artifacts: "build/app/outputs/apk/debug/*.apk"
  #       token: ${{ secrets.TOKEN }}
  build_apk:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.8.1'
    - run: flutter pub get
    - run: flutter build appbundle
    - run: flutter build apk
    - name: Upload APK
      uses: actions/upload-artifact@master
      with:
        name: apk-build
        path: build/app/outputs/bundle/release
  publish_apk:
    name: Upload Android to Firebase App Distribution
    needs: [build_apk]
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v1
    # - name: set up JDK 1.8
    #   uses: actions/setup-java@v1
    #   with:
    #     java-version: 1.8
    # - name: Download Artifact
    #   uses: actions/download-artifact@master
    #   with:
    #     name: apk-build
    - name: Upload APK
      uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
      with:
        appId: ${{secrets.FIREBASE_ANDROID_APPID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: testers
        release_notes: "a new version"
        file: build/app/outputs/apk/release/app-release.apk